### PR TITLE
upgrade to buffalo 0.12.1; upgrade npm packages

### PR DESCRIPTION
**Pull request by drnic**

### CODE REVIEW

**Comment by drnic** [comment]
Well, looking at the diff I don't see any npm package changes. Does that seem right?

**Comment by drnic** [comment]
I've also now changed `Gopkg.toml` to specifically 0.12.1 rather than development branch, like authrecipe.

**Comment by robbyoconnor** [comment]
I'm not sure -- my use-case doesn't use the frontend stuff

**Comment by drnic** [comment]
Oh well. I tested the app locally and worked as expected.

**Comment by markbates** [comment]
Thanks!

**Pull request merged**
