### PR TITLE
demostrates the use of decorator struct for a form. also reworked the tests

### PR DESCRIPTION
**Pull request by markbates**

### CODE REVIEW

**Comment by markbates** [comment]
@robbyoconnor here's what it looks like to wrap a db struct with a form struct

**Comment by robbyoconnor** [comment]
@markbates you're awesome :heart: :blue_heart: :yellow_heart: :green_heart:

**Comment by robbyoconnor** [comment]
This could stand to be merged @markbates :) It's a nice addition :D

**Comment by robbyoconnor** [comment]
Why not merge this?

**Pull request closed without merging**
